### ISSUE TITLE
React-rails server rendering packs

### ISSUE THREAD

**Issue by JensDebergh** [reactjs/react-rails#1001]
Help us help you! Have you looked for similar issues? Do you have reproduction steps? [Contributing Guide](CONTRIBUTING.md#reporting-bugs)

### Steps to reproduce

(Guidelines for creating a bug report are [available
here](../CONTRIBUTING.md#reporting-bugs))

### Expected behavior
Server rendering in production should work the same as in development

### Actual behavior
Server rendering in production is not the same.

### System configuration
**Sprockets or Webpacker version**: 4.0
**React-Rails version**: "~> 2.3.1"
**React_UJS version**:  "^2.5.0"
**Rails version**: "~> 5.2.0"
**Ruby version**: "2.6.3"

-------

Hey there!

I'm having this issue for a couple of days now and don't know how to fix it.

I'm getting the following error on production:

```
No such file or directory @ rb_sysopen - public/js/server_rendering-7930ba59728fe68ecc97.js
```

This error is correct since no `.js` file is present with that name.

The actual path name is: 

`packs/js/server_rendering-7930ba59728fe68ecc97.js`

Any idea where this problem is coming from? This code works perfectly in development but it seems wrong paths get assigned when deploying.

Any help in the right direction would be extremely helpful.

Kind regards
Jens

**Comment by dra1n** [comment]
Yep. Have the same issue in the test environment.

**Comment by naft-a** [comment]
I had exactly the same issue in development, running `./bin/webpack-dev-server` fixes it. Maybe webpacker does not compile the correct packs on the go?

**Comment by BookOfGreg** [comment]
The root directory is usually sorted in the `config/webpack.yml`.
Could someone post a small example project or say if they have the same issue with a stock config?

**Comment by naft-a** [comment]
@BookOfGreg My `config/webpacker.yml` is completely stock, generated by `rails webpacker:install` and I can see some differences but still have this issue:
```
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false
```

**Comment by benjaminsigidi** [comment]
> I had exactly the same issue in development, running `./bin/webpack-dev-server` fixes it. Maybe webpacker does not compile the correct packs on the go?

I confirm that this is the problem 

```ruby
./bin/webpack-dev-server

**Comment by AlexDemzz** [comment]
Did you find a solution ? having the same pb here

**Comment by KMarshland** [comment]
Note: I believe this is a different issue than the original post, but I'm posting here in case google sent you to this same page. TL;DR: use the edge version of react-rails until they cut a new release or monkey patch it.

I had a similar issue after upgrading from ruby 2.7.2 to 3.0.3. Unlike with naft-a, it works just fine without `./bin/webpack-dev-server` running, but fails when it is running, and thus my error is `No such file or directory @ rb_sysopen - http://localhost:3035/packs/js/server_rendering-a5bfcb3dc949a5ce125a.js`. I can also verify that the javascript is building properly, as going to `http://localhost:3035/packs/js/server_rendering-a5bfcb3dc949a5ce125a.js` does have the right javascript. Indeed, the root cause of this is in ruby 3 `open-uri` no longer overwriting `Kernel.open` (see [here](https://stackoverflow.com/questions/65937714/no-such-file-or-directory-rb-sysopen-for-external-url-rails-6-11-ruby-3) for more details). react-rails hadn't updated webpacker_manifest_container.rb to call `URI.open` instead of just `open` until [this commit](https://github.com/reactjs/react-rails/commit/72f6093d9879b4ec860aff0d9db0bf15b7517ce3).

Here's the kicker: that commit, which fixes things, was on 2021-01-02, whereas as of the time of this post the latest version of react-rails on rubygems.org is 2.6.1, released on 2019-12-31. As such, there are three options for how to fix this:

1. Use the edge version, ie `gem 'react-rails', git: 'https://github.com/reactjs/react-rails'` in your gemfile. This is a bit risky, as it could add instability as they do development
2. Make the edit in [that commit](https://github.com/reactjs/react-rails/commit/72f6093d9879b4ec860aff0d9db0bf15b7517ce3) manually, ie changing line 47 of lib/react/server_rendering/webpacker_manifest_container.rb to use `URI.open`. Personally I'd avoid this, as you have to do this on every machine you do dev on.
3. Monkey patch it. See below for my code, which I put in config/initializers/react_rails_patch.rb. This is admittedly a hack, but it's at least pretty limited in scope.

```ruby
module React
  module ServerRendering
    class WebpackerManifestContainer
      def open(uri)
        return URI.open(uri) if uri.start_with? 'http://'

        Kernel.open(uri)
      end
    end
  end
end
```
