### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by pioz** [reactjs/react-rails#1129]
I see that the latest commit is from a year ago and the React version used by this gem is v16 when React 18 is about to come out. So my question is: is this gem still maintained and active?

🥺

**Comment by BookOfGreg** [comment]
Yes and no.
This gem works for me, and over time I added more maintainers, and they fixed their issues and it works for them too.
Broadly speaking this gem still does all versions of React (though we don't bother bundling new versions with Sprockets since Webpack won) and does HMR and SSR and those fun tricks with some minor tweaks out of the box.

If you have a particular feature you'd like to add or a pet-bug you want to squash, then generally speaking if you have a good github history then I'll let you in. That goes for everyone reading this, if you have a good track record and either want to (A) Help others, or even (B) Just fix it for your own project / workplace / glory, then welcome aboard!

**Comment by justin808** [comment]
@pioz and @BookOfGreg, my team is available to help. I have invested in the React + Rails ecosystem since [my 2014 article about the subject](http://www.railsonmaui.com/blog/2014/10/03/integrating-webpack-and-the-es6-transpiler-into-an-existing-rails-project/). Most recently. we're maintaining and developing https://github.com/shakacode/shakapacker, the official successor to webpacker. 

@BookOfGreg if you'd like help, let me know!

**Comment by BookOfGreg** [comment]
Hi Justin, cool that you have taken over from Webpacker, I'd have thought you'd integrate react-on-rails into that?

**Comment by justin808** [comment]
Hi Greg!  Integrate react-on-rails into which project? 

Shakapacker/Webpacker should work fine with react-rails. 

Right now, Shakapacker has no direct connections to any frontend framework.

We're even making babel optional, with swc being support https://github.com/shakacode/shakapacker/pull/29.

**Comment by aschneit** [comment]
So react-rails supports the latest version (v6) of Shakapacker/Webpacker?

**Comment by paul-mesnilgrente** [comment]
Any chances to get a new release? I need this PR but I'd like pointing the gem to "master" =/ ?

**Comment by BookOfGreg** [comment]
@paul-mesnilgrente I'd love to. What I'm most interested in at the moment is finding a group of interested people that I can help grow into the next group of maintainers on this project. I'm currently doing the same with [RSwag](https://github.com/rswag/rswag/discussions/495) which has also recently been resurrected.
Would you have an interest in helping validate if the current master build is safe and bug free so we can launch it with confidence?
I've reached out to a couple interested parties as well to try get some effort going on this repo.

**Comment by paul-mesnilgrente** [comment]
I'll ask my company if they can give me some time on this :)

**Comment by son1112** [comment]
@BookOfGreg I am interested in helping to validate if the current master build is safe and bug free so we can launch it with confidence. 🥳

**Comment by BookOfGreg** [comment]
@son1112 good to hear, has anyone had the chance to test it out lately?

**Comment by BookOfGreg** [comment]
And same to you @paul-mesnilgrente, any luck with your company? If it's in use with them then happy to have contributions from someone with sponsored time.

**Comment by swrobel** [comment]
@justin808 any chance you're still willing to step in here? Your team has done such an amazing job with shakapacker!

**Comment by justin808** [comment]
I've been waiting for the official go-ahead! My team is growing, and we'd love to help out.

@BookOfGreg, and others, maybe we can meet up for a zoom call sometime?

How about you all jump on my slack, and I'll create a channel for `react-rails`.

Here's the invite: [Slack discussion channel](https://reactrails.slack.com/join/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE).

**Comment by BookOfGreg** [comment]
@swrobel I'm still looking for other maintainers than Justin, I've not been impressed by the description of what his vision for this gem is yet. I'm hoping that others will step forward instead.
Justin if your fork becomes successful then I'd have to reasonably hand over the project.

**Comment by justin808** [comment]
Hi @BookOfGreg, can you point me to where I made such a description for a vision?

In terms of maintenance, there's work to be done to ensure good releases from the community. 

Maybe you can use what I did with Webpacker to Shakapacker as an example?
1. Clean up all the old issues and PRs. I touched on every single issue and PR in the Webpacker. https://github.com/issues?q=is%3Aopen+is%3Aissue+justin808, https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3Ajustin808
2. Release, with a good changelog
3. Participate in slack, issue, and PR discussions

Besides me, I'd contribute my staff's time to make sure this happens. 

We could all jump on zoom to discuss sometime.

How's that sound?

**Comment by justin808** [comment]
@BookOfGreg @swrobel what's the next step?

**Comment by swrobel** [comment]
@BookOfGreg I think it's awesome that Justin is stoked to take over this project. Even if he didn't already have an incredible track record, he _is_ the only one putting his hand up.

**Comment by justin808** [comment]
@BookOfGreg Any updates?

If I get the green light, my team and I will:

1. Go through every issue and triage them.
2. Triage all the current PRs.

Based on those, we'll know what the next steps are.

@swrobel any additional ideas?

**Comment by swrobel** [comment]
@justin808 I wish I had some influence here, but it seems it's all in @BookOfGreg's hands. While he has [expressed openness in the past](https://github.com/reactjs/react-rails/issues/1161#issuecomment-1041481714), it seems that his 👎🏼  to my last comment indicates his opinion may have changed, although he hasn't commented on anything here recently...

@rmosolgo I hate to drag you into this, but is there any chance you have any influence here?

**Comment by justin808** [comment]
@rmosolgo and my team have worked closely on challenging graphql-ruby pro issues! I'll reach out to him.

Consider:

1. ShakaCode has a solid reputation for maintaining open-source related to Rails, React, and webpack, in addition to many [Rust](https://github.com/shakacode?q=&type=public&language=rust&sort=) and [ReScript](https://github.com/shakacode?q=&type=public&language=rescript&sort=) projects. For sure, we want to keep that reputation.
2. ShakaCode has been doing open-source management since 2014 and plans to continue doing this for the foreseeable future. This is lower risk and excellent stability than having any individual take over.
3. Having ShakaCode maintain the project will result in **all** pull requests and issues getting **triaged** and **frequent releases**. Just look at the changelogs for [Shakapacker](https://github.com/shakacode/shakapacker/blob/master/CHANGELOG.md) and [React on Rails](https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md) for example.

Will ShakaCode create some significant new features for react-rails? Probably not soon, given the backlog of issues and PRs to triage.

I encourage @BookOfGreg to voice his objections here.

**Comment by justin808** [comment]
Bump... @BookOfGreg have you had a chance to look at this?

I've got a growing engineering team that can help with the maintenance.

For example, check out the [PRs that we've done regarding React 18](https://github.com/shakacode/react_on_rails/pulls?q=is%3Apr+react+18+).

Given that we're maintaining Shakapacker and React on Rails, we should have the right experience to get this project back on track.

**Comment by BookOfGreg** [comment]
@swrobel I'm just not interested in handing this project to Justin when he's already taken over webpacker (shackapacker) and react-on-rails. I actually don't understand why he wouldn't take the best parts of react-rails and react-on-rails and make a new major version of react-on-rail with it. He's more than skilled enough to do it and can market it effectively.

I'm not interested in his vision for it and I'm not happy with him monetising this either.
I'm also still mad at Justin's childish jabs he made about this project in his conference talks and so far every interaction I've had has been various forms of steamrolling and astroturfing.

I am open to _other people_ from the community, who don't have a financial interest in this project failing, taking over.
If I could ban Justin from commenting here I would, because he's actively putting off other people who would have contributed from doing so.

**Comment by BookOfGreg** [comment]
@justin808 I've granted you access as a member.
The best way for you to prove me wrong is to do a good job.

**Comment by justin808** [comment]
Hi @BookOfGreg, awesome to hear. My team at ShakaCode will start to help.

To be completely transparent, ShakaCode.com invests company resources to maintain open source projects for several reasons:
1. We enjoy it. Seriously.
1. Our consulting clients use these open-source projects.
1. Our open source projects have helped us connect with awesome clients over many years as a consulting company. 

So working on open source is both a hobby and a job for the Shakacode team.

**Comment by HarrisonB** [comment]
While I'm not able to commit to anything in particular, I've spent a lot of time reading over `react-rails`'s source code and would be happy to help out here.
