### ISSUE TITLE
Does react-rails support the latest version of Shakapacker/Webpacker?

### ISSUE THREAD

**Issue by aschneit** [reactjs/react-rails#1157]
Does react-rails support the latest version of Shakapacker/Webpacker (v6)? Thanks.

**Comment by justin808** [comment]
@aschneit can you give it a try? I see no reason that it wouldn't.

**Comment by scraton** [comment]
Unfortunately, if you replace `webpacker` with `shakapacker`, [this line](https://github.com/reactjs/react-rails/blob/v2.6.1/lib/react/server_rendering/webpacker_manifest_container.rb#L12) no longer works:

```ruby
      begin
        MAJOR, MINOR, PATCH, _ = Bundler.locked_gems.specs.find { |gem_spec| gem_spec.name == 'webpacker' }.version.segments
      rescue
        MAJOR, MINOR, PATCH, _ = [0,0,0]
      end
```

So you would be unable to use server side rendering with shakapacker. This `MAJOR`, `MINOR` check will need to also consider if shakapacker is installed rather than webpacker.

I'm not sure the best way forward to handle that. Perhaps check for shakapacker within the `rescue` block? Or provide another class, specifically for shakapacker (even though their APIs are currently identical)?

**Comment by BookOfGreg** [comment]
On Master it should now, next release gem will when that happens. Will leave issue open until then.

**Comment by justin808** [comment]
@BookOfGreg I'd like to get a release shipped ASAP.

What's the process so that I can ship?

**Comment by ahangarha** [comment]
React-Rails works fine with Shakapacker 6.
With #1252 there should be no missing supported feature.
