### ISSUE TITLE
Console.log From Server Side Rendering

### ISSUE THREAD

**Issue by jadmz** [reactjs/react-rails#122]
Hi,

Is there a way to print to the terminal while rendering from the server with jruby and ruby rhino? I would like to use it for debugging.

Thanks,
Joe

**Comment by bikegriffith** [comment]
+1, would be tremendously helpful

**Comment by rearadmiral** [comment]
Has anyone been able to get js stack traces? I only ever see the error's message and when it's something generic it makes it really tough to track down a problem.

**Comment by bikegriffith** [comment]
@rearadmiral I left the stack trace out intentionally.  With a little bit more work, I could update it to include a representation of the stack as an additional part of the message string, but I was really trying to just get *something* better than what we have now.  Seems like a future enhancement rather than part of this request unless others want it now.

**Comment by rmosolgo** [comment]
The error message includes the ExecJS stack trace since #215, horray!
