### ISSUE TITLE
ReactJS and Coffee

### ISSUE THREAD

**Issue by olegsobchuk** [reactjs/react-rails#188]
Hi!
I just started learn ReactJS and from the very start I have problem!
As I can see you say that React working with coffee.
my file hello.js.jsx.coffee
```javascript
HelloWorld = React.createClass
  render: ->
    `<div>
      <h1>Hello World!</h1>
    </div>`
```
and in my view:
= react_component('HelloWorld', {}, :span)
But I get error:
ReferenceError: HelloWorld is not defined
#### my source code
https://github.com/olegsobchuk/example_app

**Comment by danott** [comment]
`window.HelloWorld = React.createClass()` should get you there. You need to do this because CoffeeScript in Rails automatically executes each file in the context of an immediately invoked function to protect the global scope.

**Comment by olegsobchuk** [comment]
yes, I've tryed it, but it not working!
P.S.
I found
gem 'sprockets-coffee-react'
is it necessary using for Coffee?

**Comment by rmosolgo** [comment]
I don't think that gem is necessary. I noticed that in your [source code](https://github.com/olegsobchuk/example_app/blob/master/app/assets/javascripts/components/hello.js.jsx.coffee), `HelloWorld` isn't attached to the window (like @danott said), and that's _definitely_ necessary for exposing global objects with coffeescript .

Try this:

```coffee
@HelloWorld = React.createClass 
# ... 
```

It should have the same effect as the previous comment. 

If that's not working, put a `console.log` in your code to make sure the component code is getting reloaded successfully. We've had some issues withthe initializers. You could check out this branch: #187 and try that with different initializer code. 

Since you're not getting parse errors, it seems like the JSX is getting transformed properly!

**Comment by olegsobchuk** [comment]
@rmosolgo, Thanks!
```
@ComponentName = ....
```
working!

**Comment by rmosolgo** [comment]
glad to hear it, strange that `window.` didn't do it, they do the same thing ... :S
