### ISSUE TITLE
assets:precompile broken with initialize_on_precompile=-true

### ISSUE THREAD

**Issue by bborn** [reactjs/react-rails#192]
With `config.assets.initialize_on_precompile = false`, `React::JSX.transform_options = app.config.react.jsx_transform_options` never gets set, and I get an exception from `jsx.rb#30`. Can we move the `React::JSX.transform_options = app.config.react.jsx_transform_options` in `railtie.rb` out of the initializer block?

**Comment by rmosolgo** [comment]
Yeah, maybe you could do something like that! 

I put it there because, as I understand it, Rails takes all the configs, then runs the initializers. So, you have to let them _set_ `app.config.react.jsx_transform_options` before you pass them to the renderer. 

What if we just skipped the ceremony of `app.config.react.jsx_transform` and assigned `React::JSX.transform_options` directly?

**Comment by rmosolgo** [comment]
@bborn I'm looking into this now and trying to reproduce. What Rails version are you using? I see in Rails 4.1, `initialize_on_precompile` was removed: https://github.com/rails/rails/commit/2d5a6de

In the mean time, you could work around this by assigning `React::JSX.transform_options` directly. Does that work for you?

**Comment by bborn** [comment]
I'm working in Rails 3.

In the mean time, you could work around this by assigning
> React::JSX.transform_options directly. Does that work for you?
>

Yes, that worked fine.

**Comment by rmosolgo** [comment]
Glad that worked for you!
