### ISSUE TITLE
jQuery-ujs-style remote form submission support

### ISSUE THREAD

**Issue by ericdfields** [reactjs/react-rails#199]
I'm currently working on integrating [newforms](https://github.com/insin/newforms) into a new Rails project that will rely heavily on React. I feel it is the most complete React form library thus far. 

I'd like my final product to have similar robustness to what you can achieve with simple [data-* methods on forms](https://github.com/rails/jquery-ujs/wiki/Unobtrusive-scripting-support-for-jQuery) currently supported by [jquery-ujs](https://github.com/rails/jquery-ujs), only on my Reactive forms. 

Is this something that interests this community in any way? I think I could show some code soon and share examples. Not sure if this fits in w/ this project at all or is some sort of standalone gem (newforms-rails).

**Comment by rmosolgo** [comment]
for my part i just use `data-remote=true` and friends inside JSX, eg 

```
<form action={"/event_periods/" + this.props.event_period.id + "/bulk_check_ins"} method="post" data-remote="true">
  {/* ... */}
  <input type='submit' value='Save'/>
</form>
```

**Comment by danott** [comment]
:+1: on using `data-remote="true"` and letting Rails UJS handle it.  Works just fine.

**Comment by gauravtiwari** [comment]
@rmosolgo how do you then set react states after rails ajax call?

**Comment by rmosolgo** [comment]
When the form is submitted, I replace the form with a spinner: 

```coffee
$(document).on 'ajax:send', ->
  CheckIns.StationSpinner.start() # replaces $(".main") with a loading indicator
```

And the form submission responds with either:
  - new HTML to insert into `$(".main")` (maybe a new page, maybe the form with errors) 
  - a JS redirect with `Turbolinks.visit`

So in my case, the form is totally destroyed after submit, then totally rebuilt from the server HTML (via `<%= react_component ... %>`). The new form has some [`initial{Whatever}` props](https://github.com/planningcenter/react-patterns#setting-state-from-props) that become its state.

How's that?

**Comment by gauravtiwari** [comment]
@rmosolgo Depends on the use case I think. What are you using forms for - simple submissions? Are you updating the UI as well? Why not just use rails RJS pattern? OR ```Turbolinks.visit``` alone? I think this would be simple if you are rendering Markups.  

Personally, I think React works great where we render changed states on the page, for ex: ```A CommentBox``` OR ```A ChatBox```. As you know, it renders changed states pretty fast.  Rather than going to server and then rendering response - I first render the response straightaway from the form to UI by setting new states and then once, I get the ```JSON``` response back I update the UI (if some validation fails the UI gets updated accordingly and user sees the validation error or something).  This solves the latency problem.

**Comment by rmosolgo** [comment]
I hope you got something working! It sounds like a react-rails-forms library might be welcome, see also #73 !
