### ISSUE TITLE
components.js generated by assets:precompile is not used

### ISSUE THREAD

**Issue by rearadmiral** [reactjs/react-rails#212]
In my setup, our production environment does not have any asset-related gems and cannot compile any assets.

When I try to render a component using `prerender: true` the gem tries to use `app.assets` to find the `components.js` file but since production doesn't have the asset pipeline configuration, it just gets the plain file contents, which in my case in ES6 unbrowserified but could be coffee for some people or whatever else.

Is there a simple way to have sprockets fetch it from public/assets?  I tried a naive approach and it complained I was trying to retrieve a file outside of the asset load paths.

**Comment by rmosolgo** [comment]
I don't know of a built-in way to do it!

You can see the lambda used for getting the JS source code as a string here:

https://github.com/reactjs/react-rails/blob/master/lib/react/rails/railtie.rb#L66-L70

You could accomplish your goal by modifying the config to use `||=` instead of `=` at line 66:

https://github.com/reactjs/react-rails/blob/master/lib/react/rails/railtie.rb#L66

Then you could pass your own `app.config.react.components_js` lambda that gathers up source code from wherever you keep it.

**Comment by rearadmiral** [comment]
Okay I'll work on a PR then. Thanks

**Comment by rearadmiral** [comment]
PR opened.  Let me know if it needs any changes.

**Comment by rmosolgo** [comment]
This should be fixed in the latest react-rails (it uses the sprockets manifest in production). Hopefully we can get that other PR for SprocketsRenderer worked out!
