### ISSUE TITLE
Is props.children functional ?

### ISSUE THREAD

**Issue by nicolas-besnard** [reactjs/react-rails#223]
Is it possible to use `this.props.children` with this gem ?

I've tried this, but it's not working :

``` ruby
<%= react_component 'Sidebar', { sidebarId: 0 }, {} do %>
  <ul class="sidebar-menu">
    <li class="header">Main</li>
  </ul>
<% end %>
```

``` javascript
return (
  <section {...props}>
    {this.props.children}
  </section>
);
```

**Comment by rmosolgo** [comment]
It doesn't work that way. 

Actually the contents of the block is rendered inside the `<div data-react-class>` placeholder (kind of like a poor man's server-side render)

Source: https://github.com/reactjs/react-rails/blob/master/lib/react/rails/view_helper.rb#L23
(It's overriden if you use `prerender: true`: https://github.com/reactjs/react-rails/blob/master/lib/react/rails/view_helper.rb#L11)

If you're interested in mixing HTML strings and react components, you could consider an implementation like this one (except rename the `__html` prop to `children`):

https://github.com/reactjs/react-rails/pull/166

**Comment by pjungwir** [comment]
It's too bad that react-rails doesn't support some way of doing this, since Containment is such a useful part of [React's Composition-vs-Inheritance approach](https://reactjs.org/docs/composition-vs-inheritance.html). And what @nicolas-besnard suggested certainly seems like the most React-like way of expressing it in your Rails views. And the body should support not just HTML, but nested React components.

**Comment by BookOfGreg** [comment]
@pjungwir see #166 
Although it looks react-like, it's plain HTML not JSX at that point. I'd welcome a PR if you'd like to wrap the HTML contents of a block with some sort of loader that turns it into JSX.

**Comment by pjungwir** [comment]
Since right now it only supports HTML, then changing it to support JSX would be backwards-compatible (mostly), right? Or even nested `react_component` helpers? (Actually maybe that works already? I haven't tried it.) I might be interested in working on a PR if that user-facing design is okay with you.

**Comment by BookOfGreg** [comment]
It's useful enough that even if it was breaking, it would probably be worth cutting as a v2.5 or even v3 if we break a lot.
@pjungwir This is all yours if you'd like to take it on :) I'll be around to help if you need test/style/design help though I may not get back to you immedaitely.

**Comment by Boeing787** [comment]
If you advertise a plugin as allowing for react components, it should encapsulate basic expectations and protocols for what React does, like having children props. Too bad we found this so late in development
