### ISSUE TITLE
Javascript state not being reinitialized???

### ISSUE THREAD

**Issue by catmando** [reactjs/react-rails#328]
Am I seeing things?   It seems like the javascript state from call to call is not being reset.  In other words if I have a variable like window.foo, once I set it, it remains defined across invocations of react_component.

This is on a slightly modified branch where I am passing adding context (ctx) to RubyRacer, but I don't think this should effect anything.

**Comment by rmosolgo** [comment]
Are you talking about server rendering?

If so, then yes, all server rendering operations all reuse the same JS runtime instance.

**Comment by rmosolgo** [comment]
They're "pooled" (usually a pool size of 1) and reused:

`ServerRendering` initializes renderers: https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering.rb#L12

then gets them out of the pool to render components: https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering.rb#L16-L18

I think this is because it's slow to start up a new JS instance!

**Comment by catmando** [comment]
Seems like a huge security risk

**Comment by rmosolgo** [comment]
How so!?

**Comment by catmando** [comment]
we render a page for user 1, then we render another page for a non-logged in user.  It seems like it would be very easy to have bugs in the code where the state left behind from user 1's rendering is accessible to the second rendering.

Understand why its being done this way... but...

**Comment by rmosolgo** [comment]
Yep, it's a similar risk to using `Thread.current[:something]` in Rails. If you don't clean up, you could be in trouble :S Feel free to improve documentation or code if you have a an improvement in mind!
