### ISSUE TITLE
Reload ExecJS Context when files changed in development

### ISSUE THREAD

**Issue by mizchi** [reactjs/react-rails#333]
It is a feature request (or question if I don't know this way).

JavaScript context Initialize with `files: ['react.js', 'component.js']` run only at first time (I read so. Is it right?)
This makes diff initial server template and updated client template. I have to reload to apply.

I made components.js like this.

```
js/src/components.js -> (browserify with babel) -> app/assets/javascripts/components.js
```

**Comment by h-michael** [comment]
:+1:

**Comment by rmosolgo** [comment]
Hmm, I expect this to Just Work :tm: because of this `to_prepare` handler: https://github.com/reactjs/react-rails/blob/master/lib/react/rails/railtie.rb#L67

That causes all the old renderers to die and makes new ones: https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering.rb#L10-L13

Is it not working for you? Maybe `to_prepare` doesn't work the way I think it does?

**Comment by catmando** [comment]
it does not work for us either...

**Comment by catmando** [comment]
Okay I spent 3 hours on this today, and figured this out:

a) it does work (at least in version 9)
b) however you might have to do something like this
`config.watchable_files.concat Dir["#{config.root}/app/views/**/*.rb"]` (or.jsx or whatever)

In our case it was not working because we are using opal (ruby on the client - .rb files) and we keep the files in app/views.  Rails does not normally look for changes to .rb files in this location so was not triggering the reloading.

To test if you have this situation try this:

a) change one of your client react files... reload the browser.  Does the code change in prerendering?  If it does then why are you reading this?
b) if the code does not change in prerendering, try now changing some rails file (like a controller).  Reload the browser.  If prerendering now gets reloaded then its just a matter of rails not seeing your file changing (changing the controller forces the reload.)
c) if it still doesn't reload the prerenendering env. then there is something else wrong with your configuration (not sure what as its is pretty simple.)

**Comment by rmosolgo** [comment]
I expect this to work for jsx files thanks to this line: 

https://github.com/reactjs/react-rails/blob/3fe755e32dd8872f89e8b25fd432154107b4aba3/lib/react/rails/railtie.rb#L25

If someone is having trouble with that, feel free to reopen this issue. If you'd like to watch more files by default, a patch is welcome!

**Comment by rmosolgo** [comment]
Using FileUpdateChecker in 2.0 will be more configurable and also catch newly-added files: #682
