### ISSUE TITLE
`<pre>` tags pre-rendered with a newline followed by indentation causing unwanted space.

### ISSUE THREAD

**Issue by remybach** [reactjs/react-rails#396]
Pre-rendering the following using react-rails 1.4.2 (at time of writing):

```jsx
var Foo = React.createClass({
  render: function() {
    return (
      <pre>Foo</pre>
    );
  };
});
```

Yields the following output:

```html
<pre data-reactid=".1mfdnglnocg.2.1:0.0.1.3">
        Foo</pre>
```

Rendering with react.js on the frontend yields the following (expected) output:

```html
<pre data-reactid=".g1b9p00xz4.2.1:3.0.1.3">Foo</pre>
```

**Comment by rmosolgo** [comment]
:cry:  how strange ... where could that be coming from ... A couple questions: 

- Can you see the compiled JavaScript for that component? Does it have any extra whitespace?
- Which transformer are you using, `JSXTransformer` or `BabelTransformer`?

**Comment by remybach** [comment]
+ The only place I'm seeing the extra whitespace is the pre-rendered output on the page (it's there when I view-source). Is that what you mean?
+ I haven't specified any particular one, so I'm guessing it's the `BabelTransformer` since that's the default.

**Comment by rmosolgo** [comment]
I'm just trying to think where that extra whitespace might come from. 

The actual call to `renderToString` is quite simple: https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/exec_js_renderer.rb#L18

So I feel like it must be added somewhere else, I'm just not sure where. That's why I asked about the JavaScript source of the component. The places I can imagine it getting inserted are:

- JSX -> JS transformation (which you could tell by looking at the `foo.js` file loaded in the browser 
- Server rendering step (I'm not sure how you'd see _just_ the output from this step)
- Template processor step (don't slim & haml mess with your whitespace sometime?)

So, if you can see the compiled version of `Foo` component, we could rule out that first possibility 

Also, could you share the surrounding view code where it is rendered?

**Comment by remybach** [comment]
Ha ha... wow... your third point was the clincher.

Fixed by basically doing:

```haml
= preserve do
  = react_component('Foo', {}, { prerender: true })
```

Thanks for pointing me in the right direction!

**Comment by rmosolgo** [comment]
Great, glad we found it! I've never run into that issue but I remember reading about it somewhere...
