### ISSUE TITLE
Babel links are broken in README

### ISSUE THREAD

**Issue by jraines** [reactjs/react-rails#399]
Seems babel rearranged their webpage, and the links here are broken:
https://github.com/reactjs/react-rails#babeltransformer-options

**Comment by jraines** [comment]
Also, apologies if I've missed something obvious, but I don't know much about Babel and I cannot figure out what to put in the `:optional` config to make it work.

Currently I'm using the names of transformers listed here, with no success:

http://babeljs.io/docs/plugins/preset-es2015/

**Comment by DanCouper** [comment]
*This is old, but might as well leave this comment here for posterity for anyone else having issues*. The links are still broken: I would have PRed them back in, but I'm not quite sure of how stable they'll be, and I think in addition that there needs to be some kind of explanation as to why it's difficult to locate the configuration documentation.

You didn't miss anything obvious. [ruby-babel-transpiler](https://github.com/babel/ruby-babel-transpiler) uses Babel 5, not Babel 6. Between 5 and 6, Babel changed significantly; it is now plugin-based. Babel currently doesn't really do much without the plugins, with those installed via NPM. Using the transformer names listed on the current site won't work, because those transformers don't exist and cannot be installed.

The v5 options are ~~hidden~~ visible in the v5 docs on that branch of the babel website repo. Here is the list of options available, for example: https://github.com/babel/babel.github.io/blob/862b43db93e48762671267034a50c30c00e433e2/docs/usage/options.md

Here are the transformers that can be passed to `optional`: https://github.com/babel/babel.github.io/tree/862b43db93e48762671267034a50c30c00e433e2/docs/advanced/transformers#optional

**Comment by BookOfGreg** [comment]
There are currently only 3 mentions of Babel in the readme on Master, going to close this for now but there are definitely updates that could happen to the docs around this gem, would welcome a PR to help with doc updates.
