### ISSUE TITLE
Link to show page

### ISSUE THREAD

**Issue by ACPK** [reactjs/react-rails#400]
If I'm using react-rails for the index, how do I link to the show page? The link below needs the path.

```
<a href={this.props.post.id}></a>
```

**Comment by rmosolgo** [comment]
If it were a Rails template, you might use `item_path(item)` to generate the link. But since we don't have access to that path from JavaScript, we have to find another solution. The two options I've used are: 

- Pass the route in as a prop, then build the URL, so your example might be:

  ```jsx
  <a href={this.props.postsPath + "/" + this.props.post.id}></a>
  ```

- Hardcode the URL. Use the `/rails/info/routes` page to determine what the URL _should_ be, then write it as a string in the JS code. For example:

  ```jsx
  <a href={"admin/posts/" + this.props.post.id}></a>
  ```

I've never tried it, but a third option could be something like [JsRoutes](https://github.com/railsware/js-routes#usage), which brings Rails route helpers into JavaScript. If hardcoding is not feasible or too risky, that might be a good solution!
