### ISSUE TITLE
Asset pipeline `require` not working with coffeescript [v1.4.2 and above]

### ISSUE THREAD

**Issue by tmikoss** [reactjs/react-rails#415]
Calling `#= require ./other_file`, in a `.js.jsx.coffee` file no longer seems to work in version 1.4.2 and above. The file is not evaluated - tested by putting a `console.log` at the top of the required file.

Changing the extension to `.js.jsx` and calling `//= require ./other_file` works as expected.

Last version of `react-rails` where it worked as expected was `1.3.3`.

Setting `config.react.jsx_transformer_class = React::JSX::JSXTransformer` does not fix the issue.

**Comment by rmosolgo** [comment]
Hmm if file extensions makes a difference, I bet it's related to 

https://github.com/reactjs/react-rails/pull/385
https://github.com/reactjs/react-rails/pull/411

**Comment by tmikoss** [comment]
Glanced over the changes in those two, but there's nothing that stands out as problematic to me. However, I'm not an expert on how the asset pipeline works.

I've created a minimal app that reproduces the issue - https://github.com/tmikoss/react-rails-coffeescript-require-example

**Comment by rmosolgo** [comment]
Man, it's been a weekend of Sprockets-wrangling. 

Thanks the the demo project. I cloned it locally and started it up. Sure enough, I only got the three log statements. So I pointed it at my local `react-rails` and started poking and prodding. 

### Some things I noticed 

- In Sprockets 3, [CoffeeScript uses the "old" engine feature](https://github.com/rails/sprockets/blob/3.x/lib/sprockets.rb#L122-L124), but JSX is set up as a mime-type + transformer (the "new" way). 
- On Sprockets master [CoffeeScript uses the "new" way](https://github.com/rails/sprockets/blob/master/lib/sprockets.rb#L151-L155)

It makes me think that somehow our transformer doesn't play well with the engine scheme. 

### Some things I tried 

- Added a test for `#= require` in `js.jsx.coffee`. It worked but that's because I'm testing with Sprockets 2. 
- Mostly, I tried tweaking stuff in `engine.rb`
  - Adding the `.js.jsx.coffee` extension to the CoffeeScript mime-type (didn't work, that was before I realized how different Sprockets 3 vs master was)
  - Registering the JSX _engine_ along with the transformer (didn't work)
  - Registering the CoffeeScript processor as a transformer (didn't work) 
  - Manually adding the `Sprockets::DirectiveProcessor` for `.js.jsx.coffee` (didn't work)

So far, nothin! But it has to be, has to be, has to be, something related to engines vs. transformers. 

I've got to get a failing spec in the repo. I'm going to try making some gemfiles with sprockets 3 _and_ Sprockets 2!

**Comment by rmosolgo** [comment]
I opened an issue an issue on Sprockets to see if that team has any suggestions: https://github.com/rails/sprockets/issues/231

**Comment by rmosolgo** [comment]
Tried this again in hopes that it would have been fixed by some work in the last few months, and it seems like it was: 

```
~/code/react-rails-coffeescript-require-example $ bundle update react-rails
# ...
# ... 
Using railties 4.2.5
Installing sprockets-rails 3.1.1 (was 2.3.3)
Using coffee-rails 4.1.0
Installing react-rails 1.8.0 (was 1.5.0)
Using rails 4.2.5
Bundle updated!
```

![image](https://cloud.githubusercontent.com/assets/2231765/16491648/c66e6178-3eac-11e6-9ed1-bf84f21ebbd5.png)

:tada: 

Since the previous update _also_ bumped `sprockets-rails`, I locked `sprockets-rails` to `~> 2.0` and tried again: 

```
~/code/react-rails-coffeescript-require-example $ bundle update sprockets-rails
# ... 
Using sprockets-rails 2.3.3 (was 3.1.1)
# ... 
```

![image](https://cloud.githubusercontent.com/assets/2231765/16491738/1adffcda-3ead-11e6-81c5-f508f85c7a31.png)

🎊 

@tmikoss , Are you able to update to the latest react-rails? OK to close this?
