### ISSUE TITLE
React.render is deprecated

### ISSUE THREAD

**Issue by inchr** [reactjs/react-rails#432]
When I load a component with react-rails I get this warning:
Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.

Why ? I've checked and I'm running react-rails 1.5.0(that in theory is updated to react 0.14.3)

**Comment by smnplk** [comment]
Same issue here.

**Comment by SylarRuby** [comment]
Show us some code

**Comment by rmosolgo** [comment]
I'm running 1.5.0 without any warnings. I can think of a few things to try:

- Make sure to restart your development server after installing the new gem. Otherwise, it might serve an old version of the assets. 
- Application code may be using `React.render`, you should update to `ReactDOM.render`. 
- You may have a dependency (like a React component you downloaded) which uses `React.render`. You can search your dependencies and update any of them which use the old API.

If those don't help you, please paste the full stack trace here -- that will show the exact line where the `React.render` call is coming from. You can see the full trace by expanding the warning (Chrome): 

![warning](https://cloud.githubusercontent.com/assets/2231765/12066180/56baf4ac-afb1-11e5-963c-440635ec76ae.gif)

**Comment by smnplk** [comment]
I'm using react-rails in combination with browserify-rails. I scanned the react_ujs code and I see where it is using React.render instead of ReactDom.render, so I just had to add sprockets import //= require react before //= require react_ujs and there is no more warning. 

But after //= require react_ujs I am also doing //= require components where I need to require React via node module system: 

var React = window.React = require('react'); 

I hope this does not compile two same versions of react library into  application.js file and makes react code load twice.  Need to check that.  Thanks for the tips @rmosolgo

**Comment by smnplk** [comment]
Oh, moron me. I was setting the ReactDom variable instead of ReactDOM :facepunch:  Issue solved :) 

@inchr , all you need to do is require ReactDOM.

**Comment by inchr** [comment]
Sorry guys, I was offline for holidays...
I've fixed following the @smnplk suggestions, but my code it's like this:

window.ReactDOM = require('react-dom');

(in my main.jsx, that is the entry point of webpack...I load react from webpack too, and I load the react-ujs after the bundle of webpack)

**Comment by lokeshjain2008** [comment]
@inchr If all good then close this issue.

**Comment by inchr** [comment]
@lokeshjain2008 Oh sorry, my fault! I'm new in github! done!
