### ISSUE TITLE
React with rails issue

### ISSUE THREAD

**Issue by sunagr1986** [reactjs/react-rails#454]
I am newby in rails and react project. I have installed all the required gems of react in rails project. when i try to render the request like this

ReactDOM.render(
  <Hello name="World" />,
  document.getElementById('container')
);

it shows me the error like 

Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.

**Comment by rmosolgo** [comment]
Hi, welcome! 

I have a couple suggestions. 

1. Instead of rendering components with `ReactDOM.render`, how about using the `react_component` view helper which is provided by `react-rails`? To use it, do this:

  - Write your React component in `/app/assets/javascripts/components/`
  - Require your component in `application.js` with `//= require components/my_component`
  - In the view, use the `react_component` helper with the component's name & props. For example, 

    ```ruby
    <%= react_component("MyComponent",  {my_prop: "my_value"}) %>
    ```

2. In your example, there first argument to `ReactDOM.render` is missing. Where is the component which you want to render?


3. Make sure the JavaScript runs _after_ `#document` has been rendered. For example, this _does not_ work:
 
   ```html
    <script>document.getElementById("container")</script>
    <div id="container"></div>
    ```

   but this _does_ work: 

   ```html
    <div id="container"></div>
    <script>document.getElementById("container")</script>
    ```

   If the JS runs _first_, it won't find the `<div>` because it has not been rendered yet!

**Comment by lfaire** [comment]
Can two different components rendered through react_component() share state ? Would one re-render if the other changes the state?

**Comment by rmosolgo** [comment]
If you're still looking for a way to communicate between unrelated components, have a look at Flux :)
