### ISSUE TITLE
PJAX support

### ISSUE THREAD

**Issue by QuantumKing** [reactjs/react-rails#489]
Is there a way to use this project with pjax?

**Comment by rmosolgo** [comment]
Yes, it's possible, although it's not supported out of the box! 

To support it in your app, you'll want to respond to the right [pjax events](https://github.com/defunkt/jquery-pjax#events) by calling functions on `ReactRailsUJS`. 

See how we setup handlers for turbolinks events?

https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_turbolinks.js#L5-L6

You want to do something similar for the analogous events in pjax. 

In fact, if you get it hooked up, that would be a great PR into react-rails :smile: ! You can see how we detect some other Javascript libraries here, then setup their support:

https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_event_setup.js#L14-L26

I think you could detect pjax there, too!

**Comment by QuantumKing** [comment]
@rmosolgo Thanks! I'll see if I can make a PR for this

**Comment by QuantumKing** [comment]
Added pjax support here https://github.com/reactjs/react-rails/pull/490

**Comment by QuantumKing** [comment]
@rmosolgo It works but I get the error "React attempted to reuse markup in a container but the checksum was invalid." when mounting components after using the browser's back/forward

**Comment by rmosolgo** [comment]
Hmmm ... As you can guess, that means that the initial render found a _different_ output than what was in the DOM, even though the existing elements _looked_ like a React result. 

Does pjax maintain a page cache? I wonder if it's inserting cached React stuff or something. 

Does it give that error if you go back and forth without _changing_ anything inside react components, or only when you alter their state?

To test whether it's caching, you could try it with cache of 0. 

Hmm... if that's what turns out to be, I'm not exactly sure to handle it (I don't remember how it works with Turbolinks)

**Comment by QuantumKing** [comment]
I believe pjax maintains a cache.

My component is very simple for testing puposes. Its simply `<div>hello</div>` so there is no state.

I tried setting `maxCacheLength: 0` in pjax options but it made no difference.

**Comment by QuantumKing** [comment]
I'm able to get rid of the error by doing
```js
node.innerHTML = ''"
```
inside `ReactRailsUJS.mountComponents` before the render statement. That way whatever was rendered and cached is wiped clean before mounting. Not sure if this leads to other problems...

**Comment by QuantumKing** [comment]
Another thing that works is removing the `data-reactid` attribute from the cached component's children.

**Comment by QuantumKing** [comment]
One solution will display the cached component (removing `data-reactid`), the other will re-render it with any new data from the server. I suppose displaying the cached version is more in line with what pjax does...?

**Comment by QuantumKing** [comment]
Which is better in your opinion? @rmosolgo

**Comment by rmosolgo** [comment]
Hmm... neither one seems _awesome_, messing with React's DOM output is a bit of a no-no. What I really want to do is get a little dummy app running with PJAX and debug it..!

**Comment by rmosolgo** [comment]
I finally got a chance to set up a pjax app, then I rebased this on master and POOF! It just worked :D 

I think this was fixed by v15: 

![image](https://cloud.githubusercontent.com/assets/2231765/14834891/df320a08-0bd4-11e6-974d-386287d4d6b2.png)

The Facebook gods have smiled on us :P 

Rebased in #518
