### ISSUE TITLE
React-Rails loads in Development but not Production 

### ISSUE THREAD

**Issue by amphithere** [reactjs/react-rails#535]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Hello, thank you so much for looking and helping!
I've been browsing the internet in search of ways to figure out why it won't work in production and I have no idea.

I get these issues:
`Uncaught Invariant Violation: _registerComponent(...): Target container is not a DOM element.`

`Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).`

and

`Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`

I had done `bundle exec rake assets:precompile RAILS_ENV=production` multiple times but it still only works in development. 

Here's a link to my production file:
https://github.com/amphithere/ResearchMap/blob/master/config/environments/production.rb
I put config.react.variant as :development because I was getting the minified error in the console when I had it as :production.

I even looked at other github web apps that use react-rails and tried their production settings, but it still gives me those errors in production. 

Thank you so much for taking a look at this, and thank you so much for your help!

**Comment by rmosolgo** [comment]
Hi, thanks for sharing a link to the app. That's very helpful. I have some ideas on the error message __but__ I don't know why it would work in development but not production!

- `Uncaught Invariant Violation: _registerComponent(...): Target container is not a DOM element.` 

  I think this is caused when you call `ReactDOM.render(<Something />, null)`. This could be happening here: 
  https://github.com/amphithere/ResearchMap/blob/master/app/assets/javascripts/components/accepted_trip_passes.js.jsx#L110-L113

   ```js 
  ReactDOM.render(
    <AcceptedTripPasses data = {this.data}/>,
    document.getElementById('accepted')
  );
  ```

  That will be executed _immediately_ by the browser. So, since the script tag is in the `<head />`, the `<body />` won't be loaded yet. 

  If you want to render React components inside Rails views, I suggest the `react_component` helper which is documented in the readme. 


- `Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined` / `Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components)`

  I think this happens when you put a component in JSX which isn't actually defined, for example 
  
  ```js
  <window.NonSenseComponent /> // NonSenseComponent is undefined 
  ```

  I think that could happen here: 
https://github.com/amphithere/ResearchMap/blob/master/app/assets/javascripts/components/conversation.js.jsx#L55

  because `<Converstation />` is rendered at the bottom of that file (likely with the same error described above). 

  When you `//= require_tree`, I think sprockets requires files in A-Z order. So, during `conversation.js.jsx`,  `message_list.js` has not been loaded yet. 

  To solve this problem, make sure to require your dependencies at the top of the file, for example:  `//= require ./message_list`. 

  (Also, if you use the `react_component` view helper, `render` won't be called until _after_ the JS is loaded, so that error might go away)


I hope some of those suggestions help, let me know!

**Comment by amphithere** [comment]
Oh my goodness! Thank you so much! That was the problem!
I appreciate your help so much, thank you!
