### ISSUE TITLE
Rails 5 / Turbolinks - Component doesn't render after being cached by turbolinks

### ISSUE THREAD

**Issue by travisdmathis** [reactjs/react-rails#563]
Help us help you! Please choose one:

- [] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [X] I have another issue to discuss.

-------

react.self-728214d….js?body=1:1064 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ListJob component.

This happens when I've mounted a component and it has been cached using turbolinks. If i browse away from the component and return to the page the component is still in the same state it was when I left and the component is never mounted again.

If i refresh the page, or remove turbolinks everything works as expected.

Rails 5rc2
react-rails 1.8
Turbolinks 5
flux

**Comment by rmosolgo** [comment]
In general, this happens when a React component is left in JS memory even after it has been removed from the DOM. For example, an AJAX handler may retain a reference to `this` and call `setState` on it, which would trigger that warning. Could something like this be happening with `ListJob`? 

Another possibility would be that we're handling the wrong events for Turbolinks 5. Here are the handlers, does that look like the right events?

https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_turbolinks.js#L5-L6

If you [opt out of caching](https://github.com/turbolinks/turbolinks#opting-out-of-caching) do you still get the error?

**Comment by travisdmathis** [comment]
If i remove turbolinks(turn off caching) i do not get the error and everything works as intended.

**Comment by rmosolgo** [comment]
What if you keep Turbolinks but add 

```
  <meta name="turbolinks-cache-control" content="no-cache">
```

As described in the "Opting out of Caching" section of the turbolinks docs?

(I'm wondering whether the issue lies with Turbolinks 5 caching in particular)

**Comment by travisdmathis** [comment]
It still happens even with no-cache enabled.

**Comment by travisdmathis** [comment]
just wanted to leave this here, i'm not doing anything that should be causing this. Looks like every other component I had built in the past with rails 4 / react-rails

**Comment by rmosolgo** [comment]
```
  componentWillUnMount: function() {
```

Does the capitalization matter here? In the docs, it's [`componentWillUnmount`](https://facebook.github.io/react/docs/component-specs.html#unmounting-componentwillunmount), is it possible that it's not finding that lifecycle hook, then never removing the event listener?

**Comment by travisdmathis** [comment]
that was it.. type-o thanks for catching that!
