### ISSUE TITLE
Global namespace not work as expected

### ISSUE THREAD

**Issue by hieuhlc** [reactjs/react-rails#570]
Help us help you! Please choose one:

- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.

-------

These are my codes.

<img width="935" alt="screen shot 2016-07-14 at 10 28 49" src="https://cloud.githubusercontent.com/assets/4828178/16827137/d4ff2bd0-49ad-11e6-8355-e0b6b73888de.png">

Currently file `main.es6.jsx` is rendering Header from `Recommended` instead of `Projects` although I registered global namespaces for them in file `components.js`. I don't know how this could happen?

**Comment by hieuhlc** [comment]
If I use prefix on React component name it works. But I prefer not using prefix when component is specified clearly in global namespaces.

<img width="405" alt="screen shot 2016-07-14 at 10 40 54" src="https://cloud.githubusercontent.com/assets/4828178/16827308/7f6e7c96-49af-11e6-9875-3ca922551807.png">

**Comment by rmosolgo** [comment]
It seems like a conflict between global `Header` variables, when you assign: 

```js
// projects/header.js
const Header = React.createClass(...)
// ...
// main.js
const Header = Components.Relationships.Projects.Header 
// ...
// recommended/header.js
const Header = React.createClass(...)
```

Aren't those _all_ assigning global `Header` variables? Then, when `Main` is rendered, it reaches for the global `Header`, which returns the last component which was assigned to that name.

I don't really know how `const` works in this context, but I bet each file is "compiled" by Babel separately, so it doesn't recognize the conflicting `const` assignments. 

There are a few ways to test whether it's a conflict in the global namespace: 

- Load your app in the browser, open the js console, and evaluate `Header`, do you get `Recommended.Header`? 
- Wrap your files in IIFEs, does that make the problem go away? For example: 

  ```js 
  (function() {
    const Header = React.createClass(...)
    Components.Stuff.Header = Header
  }())
  ```

  That forces `Header` to be within the function's scope, not the global scope. 
- Instead of assigning to `const Header`, assign components right to the namespace. For example: 

  ```js
  Components.Stuff.Header = React.createClass(...)
  ```

  When rendering, you can use the component name with dots: 

  ```js
    <Components.Stuff.Header />
   ```


  That way, they don't compete for the global `Header` identifier.

Do any of those approaches make the bug go away? If so, then I think it's because global `Header` is being overwritten by later files!

**Comment by hieuhlc** [comment]
Yes, after few mins I understood the way react-rails process jsx files. All files in `components` will be transform into ES5 JS. Every `const` will become `var` in global scope. This is what I did:
- Tested in JS console, confirm the conflict is real.
- Assigned components right to the namespace. Worked.
Btw it's a surprise that we can render components like this `<Components.Stuff.Header />`
