### ISSUE TITLE
RSpec render_component helper

### ISSUE THREAD

**Issue by antoniusostermann** [reactjs/react-rails#586]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

---

How do you integrate react-rails into rspec controller tests? In my controller specs, I'd love to have a helper, which would enable sth like:

``` ruby
get :new 
expect(response).to render_component('MyComponent')
```

**Comment by Drowze** [comment]
I support this request.  
In fact, I tried to achieve a similar result but had trouble mocking controller's `render` method. I do not currently know how to effectively a controller using `react-rails` custom renderer.

**Comment by BookOfGreg** [comment]
Hi,
Been a while since any activity on this thread but trying to get through what I can now.
I'd certainly welcome anyone to submit a PR that adds an Rspec and Minitest helper that could be manually required in, it would be good to have testing helpers that come with the gem, perhaps go so far as to have a test template generated with the components?

**Comment by BookOfGreg** [comment]
`assert_react_component` was added in https://github.com/reactjs/react-rails/pull/957
