### ISSUE TITLE
Require additional component

### ISSUE THREAD

**Issue by alienxp03** [reactjs/react-rails#599]
- [x ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.

---

I'm using the steps defined in [this issue](https://github.com/reactjs/react-rails/issues/510#issuecomment-207790440) to include the `react-modal`, but I'm getting error `Uncaught TypeError: Cannot read property 'createFactory' of undefined` in the code below:

```
'use strict';

  var React = __webpack_require__(2);
  var ReactDOM = __webpack_require__(3);
  var ExecutionEnvironment = __webpack_require__(4);
  var ModalPortal = React.createFactory(__webpack_require__(5)); // error here
```

Here is my `application.js` file:

```
//= require jquery
//= require jquery_ujs
//= require bootstrap-sprockets
//= require turbolinks
//= require moment
//= require bootstrap-datetimepicker
//= require react
//= require react_ujs
//= require components
//= require ./vendor/react-modal-v1.4.0.js
```

Based on the error, it doesn't recognise the `React` class? Did I do anything wrong?

Or is there any other way to use other React components in Rails + React app?

**Comment by rmosolgo** [comment]
This looks like a bug in the `dist/` file, which was fixed by this commit: 

https://github.com/reactjs/react-modal/commit/d3475476d149ff6bd42b1004cb35264d506871f3

Sadly, 1.4.0 has the bug and no new version has been released! 

I recommend one or all of these options: 

- Clone the repository locally, then build a new version of `dist/` for your use (by navigating to the project root and running `npm install && ./scripts/build`, [docs](https://github.com/reactjs/react-modal/blob/master/CONTRIBUTING.md#build)) 
- Open an issue on the project requesting a new release which includes that commit. I bet the maintainers will be happy to do it, but they might not know that someone wants it!

**Comment by alienxp03** [comment]
Thanks @rmosolgo. Seems like you're right on that. Maybe I can open a PR for that too :)
