### ISSUE TITLE
Get issue: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by okolomoets** [reactjs/react-rails#671]
Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded.

Got this error after upgrade gem to version 1.10.0. Old version (1.9.0) works correctly.

**Comment by rmosolgo** [comment]
Are you adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded?

If you want to debug this, please share some info:

- the source of the component which raises this error 
- how you load React.js into your app 
- anything else you tried to debug

**Comment by pan** [comment]
try to remove the line `//= require react-server` from `javascripts/component/server_rendering.js` and see if it helps.

**Comment by gamesover** [comment]
Hi @pan , it does work for me though I am no idea why. Thank you.

**Comment by joeltaylor** [comment]
I ran into this same issue. While removing `react-server` from `server_rendering.js` does stop the error, it breaks server-side rendering. 

Since mine also broke on an upgrade, I discovered that the real issue was due to using the [legacy api for string refs](https://facebook.github.io/react/docs/refs-and-the-dom.html#legacy-api-string-refs). Figured I'd add this in case it helps anyone else.

**Comment by RoRroland** [comment]
@pan it does solve my issue. Thanks a lot.
