### ISSUE TITLE
Call ReactRailsUJS.mountComponent

### ISSUE THREAD

**Issue by krazyjakee** [reactjs/react-rails#726]
- [x] I have another issue to discuss.

-------

Call `ReactRailsUJS.mountComponents()` from outside webpack.

I ajax in the next page, when it comes in I need to trigger react_ujs to mount the components on it. I do this outside webpack as I'm just using webpack for react. How do I get at this locked-down functionality?

**Comment by rmosolgo** [comment]
Webpack prevents you from attaching variables to the global scope. It's technically a _feature_ since it avoids naming conflicts. But you can work around it by attaching `ReactRailsUJS` to `window`: 

```js
var ReactRailsUJS = require("react_ujs")
window.ReactRailsUJS = ReactRailsUJS 
```

If fact, `react_ujs` does this for its own purposes:

https://github.com/reactjs/react-rails/blob/master/react_ujs/index.js#L140-L144

It's required to support the `react_component` view helper!

Does that work for you?

**Comment by krazyjakee** [comment]
Yes... it really did. I don't know how it worked, but I'm not going to complain.

Thanks very much :)
