### ISSUE TITLE
Asset Pipeline and Webpacker together?

### ISSUE THREAD

**Issue by inyigo** [reactjs/react-rails#748]
Help us help you! Please choose one:

- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.

-------

We've been using `react-rails` through asset pipeline. But we've decided to use `webpacker`, but we will be introducing it one component at a time.

Can it be used together?

For example:
- we have existing components under `app/assets/javascript/components`
- can we add components to `app/javascript/components` and be used on the same page where we use the old components?

---
I've tried this and I am getting an error from console.

```
VM19065:1 Uncaught ReferenceError: Header is not defined
```

1. `Header` was rendered
2. `Header` is from `app/javascrip/components/Header` and served by webpack.

It looks like asset pipeline is looking for it and throwing that error. Has this been encountered? Is there something I can do?

- if the page only has one components source* everything seems to be fine. eg: one page uses components from webpack. or another page uses components serve by asset pipeline
* either from `app/javascript/components` or `app/assets/javascript/components`

<img width="227" alt="screen shot 2017-07-11 at 3 12 37 am" src="https://user-images.githubusercontent.com/405883/28035322-d4d1446c-65e6-11e7-842a-ced10b0b3a1c.png">
<img width="264" alt="screen shot 2017-07-11 at 3 12 17 am" src="https://user-images.githubusercontent.com/405883/28035325-d501526a-65e6-11e7-865f-7bd60d3ca208.png">

**Comment by mallen1080** [comment]
@inyigo I was having the same problem until I removed react_ujs from the asset pipline, and now I no longer get the error

**Comment by inyigo** [comment]
@mallen1080 do you have components in `assets/javascript/components` ?

**Comment by mallen1080** [comment]
@inyigo i did when i fixed the problem, but I don't anymore.  It seems like react_ujs is what react-rails uses to find the component specified in the `react_component` view helper.  So which ever bundle (asset pipeline vs webpacker) your top-level component lives in, you should be requiring react_url, and the other should be omitted, because it will look for the component and won't find it.

**Comment by BookOfGreg** [comment]
Can I consider this issue closed or is there still an outstanding problem here?

My project uses Sprockets for CSS/SCSS, Images and some small bits of JS that are sitewide, and it also uses Webpacker for all React Components.
That structure works perfectly well because I have no dependence between the code that exists in the webpack and the other assets from sprockets.

You would not be able to split your React Components if a component in Webpacker `requires` a component in Sprockets as it would not be able to see across the boundary.

It's probably possible to split React Components between Sprockets and Webpacker as long as they do not require each other too, though you would need a custom helper as the `react_component` view helper prefers Webpack if available.

**Comment by BookOfGreg** [comment]
Closing, hope the comments here help future visitors wanting to move between Sprockets/Webpacker
