### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass Rails 5.1 only when prerendering

### ISSUE THREAD

**Issue by reneweteling** [reactjs/react-rails#836]
### Steps to reproduce

Add a simple element to your /app/asstets/javscripts/components
```javascript
class JsonForm extends React.Component {
  render() {
    return (<h1>test 2</h1>)
  }
}
```

Render it in your view, works like charm
```ruby
= react_component('Rene', {testparam: 'testje'}, {prerender: false})
```

PRERender it in your view, gives me this `undefined method `[] for nil:NilClass` error
```ruby
= react_component('Rene', {testparam: 'testje'}, {prerender: true})
```

### System configuration
**Sprockets version**: 3.7.1
**Webpacker version**: 3.0.2
**React-Rails version**: 2.4.1
**Rails version**: 5.1.1
**Ruby version**: 2.4.1

-------

Setting prerenderer: true will trigger this error: `undefined method `[] for nil:NilClass`

**Comment by BookOfGreg** [comment]
Hi @reneweteling ,
If you're putting it in `/app/assets/javascripts/components`, have you modified the `webpacker.yml`, or are you using sprockets for rendering your components?

This gem prefers Webpacker if available and the default component location is `app/javascripts`

If I add this content to `app/javascript/components/JsonForm.js`
```jsx
import React from 'react'
export default class JsonForm extends React.Component {
  render() {
    return (<h1>test 2</h1>)
  }
}
```
and render this:
```
<%= react_component 'JsonForm', {testparam: 'testje'}, {prerender: true} %>
```
Then I get a rendered component.

**Comment by reneweteling** [comment]
@BookOfGreg ive just reset my git to an pre react-rails and installed everything again, just got it working about 5 min ago. It must have been something to do with sprockets vs webpacker.

There is just one thing im still a bit confused about. Im using the webpacker setup and sprockets still requirers me to have a `app/assets/javsacripts/components.js` file, mine is empty so the error will dissapear but what is that?

Thanks so much for looking into this error :)

**Comment by davetron5000** [comment]
For future google-seachers, I had this problem as well.  It was not happening locally on OSX but was happening on my CI server, despite me explicitly setting as many versions of everything as I could.

The problem was that `package.json` needed to match `Gemfile` for versions of Webpacker.  Webpacker sets something like this in `package.json` when  you set it up:

```javascript
"dependencies": {
    "@rails/webpacker": "^3.2.0",
```

This is not in your `Gemfile`, so if you `bundle update`, you'll get a shiny new version of webpacker and friends, but the webpacker JS code is still versions behind.  You will not get any sort of error.

So, I changed my `package.json` to use the updated version of webpacker (in my case 3.4.1), and things worked.  My guess is that @reneweteling's re-install of everything may have caused this to happen and that's why it fixed the problem.
