### ISSUE TITLE
Multiple mount component with fresh rails app and Turbolinks

### ISSUE THREAD

**Issue by pioz** [reactjs/react-rails#848]
### Steps to reproduce

I've created a new rails app 5.1 and add react-rails 2.4.3:

```
rails new ciccio
cd ciccio
echo "gem 'react-rails' >> Gemfile"
bundle
rails g scaffold post title body:text
rails db:migrate
```

I've create a simple React component `Hello.jsx`

```
class Hello extends React.Component { 
  componentDidMount() {
    console.log("MOUNTED")
  }
  componentWillUnmount() {
    console.log("UNMOUNT")
  }
  render() {
    console.log("RENDER")
    return(<span>Hello</span>)
  }
}

```

And I render this component on `app/views/posts/index.html.erb`

`<%= react_component('Hello') %>`

### Expected behavior
When I change page with turbolinks and return on a previous page with a React component the component should mount one time only.

### Actual behavior
Look at this gif:

![Screen](https://media.giphy.com/media/3oxHQBMBdkHb2WPKdq/source.gif)

### System configuration
**Sprockets version**: 3.7.1
**React-Rails version**: 2.4.3
**Rails version**: 5.1
**Ruby version**: 2.4.2

**Comment by BookOfGreg** [comment]
Thanks a bunch for the detailed report! I'll look into this and let you know.

**Comment by hawkzuo** [comment]
I had the same issue on my application. Moreover, I also received a warning when trying clicking the link:
`Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.` 
I temporarily removed the following line in app/assets/javascripts/application.js to get rid of that behavior.
`//= require turbolinks`
But the turbolinks will not be working after that.

**Comment by BookOfGreg** [comment]
@hawkzuo Are you running more than one copy of react-rails, or are you calling mount yourself, or are you invoking React some additional way?

This in your error seems quite unusual, I'd appreciate a small reproduction so I can take a look.
```The node you're attempting to unmount was rendered by another copy of React```

**Comment by hawkzuo** [comment]
@BookOfGreg I followed the install instructions of react-rails. I didn't change webpacker.yml or development.rb after installation. Then I used the helper `=react_component` in view to render component. In that component I created a pagination containing links to the next page. The link is a basically an <a> tag, something like 
`            <a className="next_page" rel="next" href={"/magnets/star_react?id="+this.state.star+
            "&page="+(current+1)+"&per_page="+this.state.per_page+
            "&order="+this.state.order}>Next</a>`.  
I just send a new GET request in this link instead of changing the current react component. Maybe this is the cause? Nonetheless, each time I click the link "Next", I will receive something like:
![wechat image_20180205104524](https://user-images.githubusercontent.com/22671369/35817559-5d8011a0-0a63-11e8-8013-5f493d235209.png)
But after I removed "turbolinks" in application.js, I won't receive that each time clicking the link, rather:
![after](https://user-images.githubusercontent.com/22671369/35817842-1382d046-0a64-11e8-8098-b66569827a35.png)
I'm new to React and thanks for reaching out.

**Comment by BookOfGreg** [comment]
@hawkzuo Going to work on the original issue first. Confirmed that the handle_mount is a little messed up at the moment so that needs seeing to, that might fix your issue but will have to double check when I get to it.

<img width="319" alt="screen shot 2018-02-05 at 19 18 19" src="https://user-images.githubusercontent.com/637868/35824070-90321f80-0aa9-11e8-8676-cc2067bb7769.png">

**Comment by BookOfGreg** [comment]
@pioz @hawkzuo Can you try the pre-release of this gem?
https://rubygems.org/gems/react-rails/versions/2.4.4.pre
This may fix your issue.

**Comment by pioz** [comment]
Ok, ill try tomorrow.

**Comment by pioz** [comment]
The issue is fixed for me! Thank you for your work!

**Comment by BookOfGreg** [comment]
Glad I could help :)
