### ISSUE TITLE
in react-rails project, capybara won't client-side render

### ISSUE THREAD

**Issue by English3000** [reactjs/react-rails#870]
`react-rails` project: https://github.com/English3000/crdwk

non-`react-rails` project where capybara does client-side render & similar tests pass: https://github.com/English3000/cert-CRM
tests: https://github.com/English3000/cert-CRM/blob/master/spec/features/features_spec.rb

### Expected behavior
All 3 tests should pass: https://github.com/English3000/crdwk/blob/master/spec/features/auth_spec.rb

### Actual behavior
Last 2 fail (using Firefox)

### System configuration
**Sprockets or Webpacker version**: most recent
**React-Rails version**: most recent
**React_UJS version**: most recent
**Rails version**: 5.1
**Ruby version**: 2.3

-----------------

In my project, I server-side render HTML and then hydrate (client-side render) my sign in & sign up actions.

The test should click on the hydrated button & show the error messages I see on my localhost when clicking.

The issue is after SSR, capybara never hydrates the HTML, so neither button has an action & clicking them does nothing.

**Comment by BookOfGreg** [comment]
This is likely behaviour of `capybara-webpack`'s javascript handler.
You might want to try it with another javascript driver, we use `Capybara.javascript_driver = :selenium ` on firefox and it's never had an issue.

<img width="711" alt="screen shot 2018-02-13 at 22 42 52" src="https://user-images.githubusercontent.com/637868/36177947-454ef2e2-110f-11e8-88a6-256587eef5c5.png">
Something that could be related, your JS throws an error due to trying to access `process` client-side. Sometimes errors can stop JS execution.
