### ISSUE TITLE
redirect from react component

### ISSUE THREAD

**Issue by karan101292** [reactjs/react-rails#888]
Hi, 
I need to redirect user from react component. how do I do that without using `window.location.href = '/myroute'`

**Comment by BookOfGreg** [comment]
Hi @karan101292 ,
The recommended solution is `window.location.replace`, due to back button issues.
See : https://stackoverflow.com/questions/503093/how-do-i-redirect-to-another-webpage/506004#506004

There are many other ways such as if you're using react-router, or make a request to an endpoint that redirects or anything like that.

Closing the issue as it's unrelated to this gem but hope that helps!
