### ISSUE TITLE
Composed components

### ISSUE THREAD

**Issue by krystof-k** [reactjs/react-rails#906]
We're trying to use react-rails in a situation when we have a presentational components library in React and we want to use the components to compose Rails views. However, the problem is it's not possible to nest components, which is basically what the design system is all about.

It'd be great if react-rails support something like this:

```html
<%= react_component('Card') do %>
  <%= react_component('Heading') do %>
    Card heading
  <% end %>
  <%= react_component('Button'), { kind: 'primary' } do %>
    Button
  <% end %>
<% end %>
```

resulting in this equivalent in JSX:

```javascript
<Card>
  <Heading>
    Card heading
  </Heading>
  <Button kind="primary">
    Button
  </Button>
</Card>
```

What do you think about this? Is it planned? Or is there any other recommended approach how to achieve the same result? Thanks!

**Comment by BookOfGreg** [comment]
It's been discussed in the past, currently there's no way to pass in things from the rails context to the components other than as props, if you rendered out two components and wanted to nest then, you'd need to dangerouslysetinnerhtml on it.

Someone started working on adding the ability to pass in blocks of HTML as children to the component but they seem to have dropped the effort.

Going to close for now as it's not a feature we're likely going to support. I'd recommend composing components within React rather than within Rails.

**Comment by krystof-k** [comment]
I see, that's a pity. This is the approach we will probably take, but that requires doing something in React we hoped to do in Rails.

Anyway, if anyone has an update on this, I would be happy to hear about that in this issue.
