### ISSUE TITLE
Using Rails View Helpers In React?

### ISSUE THREAD

**Issue by hasahmed** [reactjs/react-rails#913]
### System configuration
**Sprockets or Webpacker version**:
3.12.0 
**React-Rails version**:
?
**Rect_UJS version**:
?
**Rails version**:
5.1.6 
**Ruby version**:
2.5.1

-------
I want to be able to use rails view helpers from React. Is this possible?
I want to do this because as it is I need to pass a lot of things into the react component using the `react_component` view helpers hash argument, then from there I have to continue passing the objects down using props. This seems clunky and prone to error, when there is only one component in the hierarchy that worries about the object in the first place. Is there a react-rails solution to this? This would only be possible if server-render were set to true I assume. 

The specific issue that I am having looks is this:
I have a View component that is a template for the entire page. It has the Nav-Bar and the Footer and then the children of the View component that make up the rest of the page vary. The Nave-Bar component is different based on weather or not the user is logged in. As I have it currently I am passing the information down the hierarchy through props, but it seems quite clunky. I have a rails helper method. Is there any way to access it without passing it down via props?

**Comment by BookOfGreg** [comment]
Sadly not.

React and Rails can only talk through the props interface. There was an Issue open for someone to work on passing Rails html through as children but that also seems infeasable to me. Basically everything is passed to the ExecJS Runtime and it runs in isolation and returns the server-side rendered react as a string.

This must run in isolation because if you think of the client-side story, there is no Rails server for the client to access!

**Comment by ttanimichi** [comment]
> Is there any way to access it without passing it down via props?

I think you can use Redux to avoid passing objects down by using props. You can create a store and inject props to components by using `mapStateToProps`.

**Comment by hasahmed** [comment]
@BookOfGreg Yes that makes sense. Would be nice though!
@ttanimichi Cool thanks for the heads up.
