### ISSUE TITLE
Is version 1.6.0 compatible with Rails 5.2.x

### ISSUE THREAD

**Issue by kapso** [reactjs/react-rails#928]
Sorry, but we have a legacy app (really old code base) that was written in v1.6.0 (Rails 4.2.x), which we are trying to migrate into a Rails 5.2.0 application. We would like to make this work without any code changes, due to time constraints. 

Any recommendations, tips really appreciated. Thanks a lot.

**Comment by BookOfGreg** [comment]
I joined the project after v2.0 so, to be able to answer you I'd have to dig around a bit.

In general this lib depends on versions of Sprockets or Webpacker rather than Rails itself. I assume since it's an old project your pipeline will likely be Sprockets, what version is it?

You might get away with an upgrade of this gem up. Not a massive amount changed other than bugfixes for the last few months and features around Hydrate etc.

**Comment by BookOfGreg** [comment]
After looking at the v1.6 appraisals, it's using whatever Sprockets version exists in 4.2
If you can upgrade Rails from 4.x to 5.x without changing Sprockets versions it should still continue to work.

If not please let me know and I'll see if I can assist further.

In general I do recommend upgrading react-rails as there have been a couple bugfixes between 1.6 and 1.11, and again in 2.x

**Comment by kapso** [comment]
Quick update: I was able to get the app pass error free on assets pipeline using version `1.11.0` phew : ) Now testing the app functionally to make sure all is green.

Thanks @BookOfGreg for the quick response, much appreciated. I will close this after my tests. Thanks again.

**Comment by kapso** [comment]
All looks good, closing this issue. Thanks.
