### ISSUE TITLE
Updating the babel version

### ISSUE THREAD

**Issue by MECarmody** [reactjs/react-rails#944]
I know that react-rails uses the version of the `babel-source` gem, but that's been stuck on 5.8.35 since early 2016, whereas babel itself is up to 7.1.2. This has started to cause certain issues for our app that we've been able to work around so far, but I'm nervous that being married to the `babel-source` gem will eventually start to cause problems that block development.

Has anyone found a way around this? Or, is there any plan in place to move to a more recent version of babel?

**Comment by BookOfGreg** [comment]
What issues is it causing for you? I can't exactly fix a bug I can't know of.

**Comment by BookOfGreg** [comment]
I'm going to close this as I'm unable to make further progress.

I held some discussions with maintainers in the Babel repo and they didn't see why Sprockets should be supported as Webpack is an option in the ruby community now. Since Rails 6 is out and defaults to Webpacker I'm inclined to agree and they didn't allow me to take over babel-transpiler.
